#!/usr/bin/env ruby

require 'wp2hatena/hatena/oauth/app'
require 'io/console'

print 'CONSUMER_KEY：'
CONSUMER_KEY = gets.chomp
print 'CONSUMER_SECRET：'
CONSUMER_SECRET = gets.chomp

Wp2hatena::Hatena::OAuth::App.run!
